version: '3.3'

services:
  web:
    image: isharedemotest3dev.azurecr.io/web:latest
    environment:    
      FLASK_ENV: development
      DATABASE_HOST: mysql
      MAIL_SERVER: smtp4dev
      NGINX_PORT: 8080
      VAULT_URL: https://isharedemotest3dev.vault.azure.net/
      AZURE_CLIENT_ID: 157d267c-d094-42b2-bfab-482167b9037d
      AZURE_TENANT_ID: 60c86ecb-0dc3-4e40-8ef2-a9f29094215b
      AZURE_CLIENT_SECRET: Gn97Q~cCBK_7RTSndLv8ZV~.lxAEJmi-3G0wH
    ports:
      - 80:5000
    volumes:
      - ./../app:/home/pc_donation/app
      - ./../logs:/home/pc_donation/logs
    depends_on:
      - mysql

  mysql:
    image: isharedemotest3dev.azurecr.io/mysql:latest
    container_name:  dev_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - ./data-mysql:/var/lib/mysql
    cap_add:
      - SYS_NICE

  phpmyadmin:
    image: isharedemotest3dev.azurecr.io/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 5001:80

  smtp4dev:
    image: isharedemotest3dev.azurecr.io/smtp4dev:v3
    container_name: dev_smtp4dev
    restart: always
    ports:
      - '5002:80'
      - '25:25'
      - '143:143'
    volumes:
      - ./smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev
      - ServerOptions__Database=/smtp4dev/database.db
